services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
