export enum SharedTokens {
  MAIL_SENDER_PROVIDER = 'MAIL_SENDER_PROVIDER',
  HASH_SERVICE_PROVIDER = 'HASH_SERVICE_PROVIDER',
  TOKEN_SERVICE_PROVIDER = 'TOKEN_SERVICE_PROVIDER',
  LLM_CLIENT_OPENAI_PROVIDER = 'LLM_CLIENT_FIRST_PROVIDER',
  LLM_CLIENT_DEEPSEEK_PROVIDER = 'LLM_CLIENT_SECOND_PROVIDER',
  FIREBASE_NOTIFICATIONS_PROVIDER = 'FIREBASE_NOTIFICATIONS_PROVIDER',
}
