export enum MarketingTokens {
  SUBSCRIBERS_REPOSITORY = 'SUBSCRIBERS_REPOSITORY',
  ADMINS_REPOSITORY = 'ADMINS_REPOSITORY',
  CAMPAIGNS_REPOSITORY = 'CAMPAIGNS_REPOSITORY',
  LLM_RESPONSES_REPOSITORY = 'LLM_RESPONSES_REPOSITORY',
}
